export const LOCATIONS = [
  { label: "京都市北区", value: "京都市北区" },
  { label: "京都市上京区", value: "京都市上京区" },
  { label: "京都市左京区", value: "京都市左京区" },
  { label: "京都市中京区", value: "京都市中京区" },
  { label: "京都市東山区", value: "京都市東山区" },
  { label: "京都市下京区", value: "京都市下京区" },
  { label: "京都市南区", value: "京都市南区" },
  { label: "京都市右京区", value: "京都市右京区" },
  { label: "京都市伏見区", value: "京都市伏見区" },
  { label: "京都市山科区", value: "京都市山科区" },
  { label: "京都市西京区", value: "京都市西京区" },

  { label: "福知山市", value: "福知山市" },
  { label: "舞鶴市", value: "舞鶴市" },
  { label: "綾部市", value: "綾部市" },
  { label: "宇治市", value: "宇治市" },
  { label: "宮津市", value: "宮津市" },
  { label: "亀岡市", value: "亀岡市" },
  { label: "城陽市", value: "城陽市" },
  { label: "向日市", value: "向日市" },
  { label: "長岡京市", value: "長岡京市" },
  { label: "八幡市", value: "八幡市" },
  { label: "京田辺市", value: "京田辺市" },
  { label: "京丹後市", value: "京丹後市" },
  { label: "南丹市", value: "南丹市" },
  { label: "木津川市", value: "木津川市" },
  { label: "乙訓郡", value: "乙訓郡" },
  { label: "大山崎町", value: "大山崎町" },
  { label: "久世郡", value: "久世郡" },
  { label: "久御山町", value: "久御山町" },
  { label: "綴喜郡", value: "綴喜郡" },
  { label: "井手町", value: "井手町" },
  { label: "宇治田原町", value: "宇治田原町" },
  { label: "相楽郡", value: "相楽郡" },
  { label: "笠置町", value: "笠置町" },
  { label: "和束町", value: "和束町" },
  { label: "精華町", value: "精華町" },
  { label: "南山城村", value: "南山城村" },
  { label: "船井郡", value: "船井郡" },
  { label: "京丹波町", value: "京丹波町" },
  { label: "与謝郡", value: "与謝郡" },
  { label: "伊根町", value: "伊根町" },
  { label: "与謝野町", value: "与謝野町" },

];
